version: "3.9"

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_home:
  docker_certs_ca:
  docker_certs_client:

services:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    user: root
    networks:
      jenkins_network:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - docker_certs_ca:/certs/ca
      - docker_certs_client:/certs/client
      - jenkins_home:/var/jenkins_home

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    networks:
      - jenkins_network
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker_certs_client:/certs/client:ro
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
