version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - jenkins

  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    expose:
      - "2376"
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge
