version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins_network
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://dind:2375

  dind:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: unless-stopped
    networks:
      - jenkins_network
    # No ports exposed to host, but available to other containers
    volumes:
      - dind-data:/var/lib/docker
    environment:
      - DOCKER_TLS_CERTDIR=""
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins-data:
  dind-data: