version: '3.9'
services:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    networks:
      - jenkins_dind
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - docker-cache:/var/lib/docker
    restart: on-failure

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    networks:
      - jenkins_dind
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8080:8080
      - 50000:50000
    depends_on:
      - dind
    restart: on-failure

networks:
  jenkins_dind:
    driver: bridge

volumes:
  jenkins-data:
  docker-cache:
