version: "3.8"

services:
  dind:
    image: docker:24-dind
    privileged: true                          # DinD requires privileged mode
    environment:
      DOCKER_TLS_CERTDIR: ""                  # disable TLS for demo (explain risk in report)
    command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]
    volumes:
      - docker_layer_cache:/var/lib/docker
    networks:
      - ci-network

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    user: root
    environment:
      DOCKER_HOST: "tcp://dind:2375"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./groovy/security.groovy:/var/jenkins_home/init.groovy.d/security.groovy
    depends_on:
      - dind
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - ci-network
    restart: unless-stopped

volumes:
  jenkins_home:
  docker_layer_cache:

networks:
  ci-network:
    driver: bridge
